# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_logo',
            field=models.ImageField(default='', upload_to='myimages'),
        ),
    ]
